#pragma once
#ifndef _TEKSTORM_PROTOCOLTYPE_H
#define _TEKSTORM_PROTOCOLTYPE_H
#include "../BuildConf.h"

namespace Tekstorm
{
	namespace Net
	{
		enum ProtocolType
		{
			PROTOCOL_TYPE_IP,
			PROTOCOL_TYPE_IPV6HOPBYHOP,
			PROTOCOL_TYPE_ICMP,
			PROTOCOL_TYPE_IGMP,
			PROTOCOL_TYPE_GGP,
			PROTOCOL_TYPE_IPV4,
			PROTOCOL_TYPE_TCP,
			PROTOCOL_TYPE_PUP,
			PROTOCOL_TYPE_UDP,
			PROTOCOL_TYPE_IDP,
			PROTOCOL_TYPE_IPV6,
			PROTOCOL_TYPE_IPV6ROUTINGHEADER,
			PROTOCOL_TYPE_IPV6FRAGMENTHEADER,
			PROTOCOL_TYPE_IPSECENCAPSULATINGSECURITY,
			PROTOCOL_TYPE_IPSECAUTHENTICATION,
			PROTOCOL_TYPE_ICMPV6,
			PROTOCOL_TYPE_IPV6NONEXTHEADER,
			PROTOCOL_TYPE_IPV6DESTINATION,
			PROTOCOL_TYPE_ND,
			PROTOCOL_TYPE_RAW,
			PROTOCOL_TYPE_UNESPECIFIED,
			PROTOCOL_TYPE_IPX,
			PROTOCOL_TYPE_SPX,
			PROTOCOL_TYPE_SPXII,
			PROTOCOL_TYPE_UNKNOWN
		};
	}
}

#endif /* _TEKSTORM_PROTOCOLTYPE_H */